spring:
  application:
    name:
      role-base-full-stack-app
  datasource:
    url: jdbc:mysql://localhost:3307/mysqlrbac
    username: root
    password: testpw
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: core
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
