spring:
  application:
    name: rbac-ecommerce-backend
  cache:
    type: redis
  data:
    redis:
      database: 1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: core
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none

server:
  port: 9050

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

---
spring:
  config:
    activate:
      on-profile: local
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:mysql://localhost:3307/mysqlrbac
    username: root
    password: testpw

security:
  jwt:
    secretKey: superSecretKey#@somerandomhash12321@123
    tokenExpiryMin: 3600000
    issuer: rbac-ecommerce-backend
  corsAllowedOrigins: http://localhost:4200,http://localhost:9050
