spring:
  application:
    name: rbac-ecommerce-config-server

server:
  port: 8888

logging:
  level:
    org.springframework.web: INFO
    org.springframework.cloud: INFO

---
spring:
  config:
    activate:
      on-profile: local
  cloud:
    config:
      server:
        native:
          search-locations: file:${user.dir}/rbac-ecommerce-config-server/config

eureka:
  client:
    service-url:
      defaultZone: https://localhost:8761/eureka

#encrypt:
#  key-store:
#    location: classpath:localhost-keystore.jks
#    alias: localhostcert
#    password: keystorep
#    type: jks

server:
  ssl:
    key-store: classpath:localhost-keystore.jks
    key-store-password: keystorep
    key-alias: localhost
    key-store-type: jks
    enabled: true
